name: holo_card_effect
description: "ホログラムカードのような光沢効果を実装するFlutterパッケージです。傾きに応じて変化するホログラム効果、カスタマイズ可能な光沢エフェクトを提供します。"
version: 0.0.1
homepage: https://github.com/oh-yeah-sea-kit2/holo_card_effect

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/sparkles.gif
    - assets/holo.png
    - test/assets/test_image.png
